# Generated by Django 3.1.4 on 2021-01-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210106_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('IR', 'Endüstriyel Robotlar'), ('RGV', 'RGV Robotlar'), ('CO', 'Cobotlar')], max_length=4),
        ),
    ]
