# Generated by Django 3.1.4 on 2021-01-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210109_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='brand',
        ),
    ]
