# Generated by Django 3.1.4 on 2021-01-09 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_robot_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.brand'),
        ),
    ]
