# Generated by Django 3.1.4 on 2021-01-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210109_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='brand',
            new_name='brand_name',
        ),
    ]
