# Generated by Django 3.1.4 on 2021-01-09 16:19

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210109_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='application',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AW', 'Arc Welding'), ('CL', 'Cleaning'), ('CO', 'Coating'), ('CB', 'Collaboration'), ('CU', 'Cutting'), ('DB', 'Deburring'), ('DP', 'Depalletizing'), ('DC', 'Die Casting'), ('DI', 'Dispensing'), ('EN', 'Enamelling'), ('FP', 'Full Layer Palletizing'), ('GZ', 'Glazing'), ('GU', 'Gluing'), ('GR', 'Grinding'), ('HW', 'Heavy Arc Welding'), ('IM', 'Injection Moulding'), ('IP', 'Item Picking'), ('LO', 'Loading'), ('LU', 'Loading and Unloading'), ('MT', 'Machine Tending'), ('MH', 'Machine Handling'), ('ME', 'Measuring'), ('PC', 'Packing'), ('PA', 'Painting'), ('PT', 'Palletizing'), ('PI', 'Part Inspection'), ('PK', 'Picking'), ('PO', 'Polishing'), ('PW', 'Powdering'), ('PS', 'Powertrain Assembly'), ('PM', 'Pre-Machining'), ('PU', 'Press Automation'), ('PB', 'Press Brake Tending'), ('PE', 'Press Tending'), ('RI', 'Rubber Insertion'), ('SD', 'Screw Driving'), ('SE', 'Sealing'), ('SA', 'Small Parts Assembly'), ('SW', 'Spot Welding'), ('SP', 'Spraying'), ('TE', 'Testing'), ('UL', 'Unloading')], max_length=11, null=True),
        ),
    ]
