# Generated by Django 3.1.4 on 2021-01-09 19:03

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210109_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='axis1_movement',
            field=models.CharField(choices=[('R', 'Rotation'), ('A', 'Arm'), ('W', 'Wrist'), ('B', 'Bend'), ('T', 'Turn')], max_length=50),
        ),
        migrations.AlterField(
            model_name='robot',
            name='axis2_movement',
            field=models.CharField(choices=[('R', 'Rotation'), ('A', 'Arm'), ('W', 'Wrist'), ('B', 'Bend'), ('T', 'Turn')], max_length=50),
        ),
        migrations.AlterField(
            model_name='robot',
            name='axis3_movement',
            field=models.CharField(choices=[('R', 'Rotation'), ('A', 'Arm'), ('W', 'Wrist'), ('B', 'Bend'), ('T', 'Turn')], max_length=50),
        ),
        migrations.AlterField(
            model_name='robot',
            name='axis4_movement',
            field=models.CharField(choices=[('R', 'Rotation'), ('A', 'Arm'), ('W', 'Wrist'), ('B', 'Bend'), ('T', 'Turn')], max_length=50),
        ),
        migrations.AlterField(
            model_name='robot',
            name='axis5_movement',
            field=models.CharField(choices=[('R', 'Rotation'), ('A', 'Arm'), ('W', 'Wrist'), ('B', 'Bend'), ('T', 'Turn')], max_length=50),
        ),
        migrations.AlterField(
            model_name='robot',
            name='axis6_movement',
            field=models.CharField(choices=[('R', 'Rotation'), ('A', 'Arm'), ('W', 'Wrist'), ('B', 'Bend'), ('T', 'Turn')], max_length=50),
        ),
        migrations.AlterField(
            model_name='robot',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.controller'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='mounting',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A', 'Any'), ('F', 'Floor'), ('W', 'Wall'), ('T', 'Tilted'), ('I', 'Invert Mount')], max_length=30),
        ),
        migrations.AlterField(
            model_name='robot',
            name='working_range_image',
            field=models.ImageField(upload_to='robots/working_range_images/'),
        ),
    ]
