# Generated by Django 3.1.4 on 2021-01-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210109_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robot',
            old_name='overall_rating',
            new_name='performance_rating',
        ),
    ]
