# Generated by Django 3.1.7 on 2021-04-06 19:57

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210110_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis1_speed', models.IntegerField(default=1)),
                ('axis1_movement', models.CharField(choices=[('R', 'Rotation'), ('A', 'Arm'), ('W', 'Wrist'), ('B', 'Bend'), ('T', 'Turn')], max_length=50)),
                ('axis2_speed', models.IntegerField(default=1)),
                ('axis2_movement', models.CharField(choices=[('R', 'Rotation'), ('A', 'Arm'), ('W', 'Wrist'), ('B', 'Bend'), ('T', 'Turn')], max_length=50)),
                ('axis3_speed', models.IntegerField(default=1)),
                ('axis3_movement', models.CharField(choices=[('R', 'Rotation'), ('A', 'Arm'), ('W', 'Wrist'), ('B', 'Bend'), ('T', 'Turn')], max_length=50)),
                ('axis4_speed', models.IntegerField(default=1)),
                ('axis4_movement', models.CharField(choices=[('R', 'Rotation'), ('A', 'Arm'), ('W', 'Wrist'), ('B', 'Bend'), ('T', 'Turn')], max_length=50)),
                ('axis5_speed', models.IntegerField(default=1)),
                ('axis5_movement', models.CharField(choices=[('R', 'Rotation'), ('A', 'Arm'), ('W', 'Wrist'), ('B', 'Bend'), ('T', 'Turn')], max_length=50)),
                ('axis6_speed', models.IntegerField(default=1)),
                ('axis6_movement', models.CharField(choices=[('R', 'Rotation'), ('A', 'Arm'), ('W', 'Wrist'), ('B', 'Bend'), ('T', 'Turn')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='order',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='axis1_movement',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='axis1_speed',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='axis2_movement',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='axis2_speed',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='axis3_movement',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='axis3_speed',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='axis4_movement',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='axis4_speed',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='axis5_movement',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='axis5_speed',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='axis6_movement',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='axis6_speed',
        ),
        migrations.AlterField(
            model_name='robot',
            name='application',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AS', 'Assembly'), ('AW', 'Arc Welding'), ('CL', 'Cleaning'), ('CO', 'Coating'), ('CB', 'Collaboration'), ('CU', 'Cutting'), ('DB', 'Deburring'), ('DP', 'Depalletizing'), ('DC', 'Die Casting'), ('DI', 'Dispensing'), ('EN', 'Enamelling'), ('FP', 'Full Layer Palletizing'), ('GZ', 'Glazing'), ('GU', 'Gluing'), ('GR', 'Grinding'), ('HW', 'Heavy Arc Welding'), ('IM', 'Injection Moulding'), ('IP', 'Item Picking'), ('LO', 'Loading'), ('LU', 'Loading and Unloading'), ('MT', 'Machine Tending'), ('MH', 'Machine Handling'), ('ME', 'Measuring'), ('PC', 'Packing'), ('PA', 'Painting'), ('PT', 'Palletizing'), ('PI', 'Part Inspection'), ('PK', 'Picking'), ('PO', 'Polishing'), ('PW', 'Powdering'), ('PS', 'Powertrain Assembly'), ('PM', 'Pre-Machining'), ('PU', 'Press Automation'), ('PB', 'Press Brake Tending'), ('PE', 'Press Tending'), ('RI', 'Rubber Insertion'), ('SD', 'Screw Driving'), ('SE', 'Sealing'), ('SA', 'Small Parts Assembly'), ('SW', 'Spot Welding'), ('SP', 'Spraying'), ('TE', 'Testing'), ('UL', 'Unloading')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='category',
            field=models.CharField(choices=[('IR', 'Industrial Robots'), ('RGV', 'RGV Robots'), ('CO', 'Cobots')], max_length=4),
        ),
        migrations.AlterField(
            model_name='robot',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger'), ('A', 'success'), ('W', 'warning')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
        migrations.AddField(
            model_name='axis',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.robot'),
        ),
    ]
