# Generated by Django 3.1.7 on 2021-04-06 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210406_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='axis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.axis', unique=True),
        ),
    ]
