# Generated by Django 3.1.7 on 2021-04-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_axis_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='axis',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='robot',
            name='controller',
        ),
        migrations.DeleteModel(
            name='Axis',
        ),
        migrations.DeleteModel(
            name='Robot',
        ),
    ]
