# Generated by Django 3.1.7 on 2021-04-06 21:36

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210407_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Axis Info', max_length=50)),
                ('axis1_speed', models.IntegerField(default=1)),
                ('axis1_movement', models.CharField(choices=[('R', 'Rotation'), ('A', 'Arm'), ('W', 'Wrist'), ('B', 'Bend'), ('T', 'Turn')], max_length=50)),
                ('axis2_speed', models.IntegerField(default=1)),
                ('axis2_movement', models.CharField(choices=[('R', 'Rotation'), ('A', 'Arm'), ('W', 'Wrist'), ('B', 'Bend'), ('T', 'Turn')], max_length=50)),
                ('axis3_speed', models.IntegerField(default=1)),
                ('axis3_movement', models.CharField(choices=[('R', 'Rotation'), ('A', 'Arm'), ('W', 'Wrist'), ('B', 'Bend'), ('T', 'Turn')], max_length=50)),
                ('axis4_speed', models.IntegerField(default=1)),
                ('axis4_movement', models.CharField(choices=[('R', 'Rotation'), ('A', 'Arm'), ('W', 'Wrist'), ('B', 'Bend'), ('T', 'Turn')], max_length=50)),
                ('axis5_speed', models.IntegerField(default=1)),
                ('axis5_movement', models.CharField(choices=[('R', 'Rotation'), ('A', 'Arm'), ('W', 'Wrist'), ('B', 'Bend'), ('T', 'Turn')], max_length=50)),
                ('axis6_speed', models.IntegerField(default=1)),
                ('axis6_movement', models.CharField(choices=[('R', 'Rotation'), ('A', 'Arm'), ('W', 'Wrist'), ('B', 'Bend'), ('T', 'Turn')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('IR', 'Industrial Robots'), ('RGV', 'RGV Robots'), ('CO', 'Cobots')], max_length=4)),
                ('application', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AS', 'Assembly'), ('AW', 'Arc Welding'), ('CL', 'Cleaning'), ('CO', 'Coating'), ('CB', 'Collaboration'), ('CU', 'Cutting'), ('DB', 'Deburring'), ('DP', 'Depalletizing'), ('DC', 'Die Casting'), ('DI', 'Dispensing'), ('EN', 'Enamelling'), ('FP', 'Full Layer Palletizing'), ('GZ', 'Glazing'), ('GU', 'Gluing'), ('GR', 'Grinding'), ('HW', 'Heavy Arc Welding'), ('IM', 'Injection Moulding'), ('IP', 'Item Picking'), ('LO', 'Loading'), ('LU', 'Loading and Unloading'), ('MT', 'Machine Tending'), ('MH', 'Machine Handling'), ('ME', 'Measuring'), ('PC', 'Packing'), ('PA', 'Painting'), ('PT', 'Palletizing'), ('PI', 'Part Inspection'), ('PK', 'Picking'), ('PO', 'Polishing'), ('PW', 'Powdering'), ('PS', 'Powertrain Assembly'), ('PM', 'Pre-Machining'), ('PU', 'Press Automation'), ('PB', 'Press Brake Tending'), ('PE', 'Press Tending'), ('RI', 'Rubber Insertion'), ('SD', 'Screw Driving'), ('SE', 'Sealing'), ('SA', 'Small Parts Assembly'), ('SW', 'Spot Welding'), ('SP', 'Spraying'), ('TE', 'Testing'), ('UL', 'Unloading')], max_length=250, null=True)),
                ('label', models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger'), ('A', 'success'), ('W', 'warning')], max_length=1)),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='')),
                ('slogan', models.CharField(blank=True, max_length=100, null=True)),
                ('performance_rating', models.IntegerField(default=1)),
                ('customer_rating', models.IntegerField(default=1)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('working_range_image', models.ImageField(upload_to='robots/working_range_images/')),
                ('number_of_axes', models.IntegerField(default=6)),
                ('payload', models.IntegerField(default=1)),
                ('reach', models.FloatField(default=1)),
                ('repeatability', models.FloatField(default=1)),
                ('picking_cycle', models.FloatField(default=1)),
                ('mounting', multiselectfield.db.fields.MultiSelectField(choices=[('A', 'Any'), ('F', 'Floor'), ('W', 'Wall'), ('T', 'Tilted'), ('I', 'Invert Mount')], max_length=30)),
                ('weight', models.IntegerField(default=1)),
                ('axis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.axis', unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.controller')),
            ],
        ),
    ]
