# Generated by Django 3.1.7 on 2021-04-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='axis',
            name='name',
        ),
    ]
