# Generated by Django 3.1.7 on 2021-04-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_remove_axis_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='axis',
            name='name',
            field=models.CharField(default='Axis Info', max_length=50),
        ),
    ]
