# Generated by Django 3.1.7 on 2021-04-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_axis_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('attributes', models.JSONField()),
                ('attributes_kwargs', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='robot',
            name='attribute_groups',
        ),
    ]
