# Generated by Django 3.1.7 on 2021-07-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValueCalculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=350, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('extra_fields', models.JSONField(blank=True, default=dict, null=True)),
                ('library', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('config', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
