# Generated by Django 3.1.7 on 2021-07-17 08:54

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('slug', models.CharField(max_length=250)),
                ('name', models.CharField(blank=True, max_length=350, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RobotClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=50)),
                ('attributes', models.JSONField()),
                ('attributes_detailed', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('attributes', models.JSONField(default=dict)),
                ('attributes_detailed', models.JSONField(default=dict)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('IR', 'Industrial Robots'), ('RGV', 'RGV Robots'), ('CO', 'Cobots')], max_length=4)),
                ('application', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AS', 'Assembly'), ('AW', 'Arc Welding'), ('CL', 'Cleaning'), ('CO', 'Coating'), ('CB', 'Collaboration'), ('CU', 'Cutting'), ('DB', 'Deburring'), ('DP', 'Depalletizing'), ('DC', 'Die Casting'), ('DI', 'Dispensing'), ('EN', 'Enamelling'), ('FP', 'Full Layer Palletizing'), ('GZ', 'Glazing'), ('GU', 'Gluing'), ('GR', 'Grinding'), ('HW', 'Heavy Arc Welding'), ('IM', 'Injection Moulding'), ('IP', 'Item Picking'), ('LO', 'Loading'), ('LU', 'Loading and Unloading'), ('MT', 'Machine Tending'), ('MH', 'Machine Handling'), ('ME', 'Measuring'), ('PC', 'Packing'), ('PA', 'Painting'), ('PT', 'Palletizing'), ('PI', 'Part Inspection'), ('PK', 'Picking'), ('PO', 'Polishing'), ('PW', 'Powdering'), ('PS', 'Powertrain Assembly'), ('PM', 'Pre-Machining'), ('PU', 'Press Automation'), ('PB', 'Press Brake Tending'), ('PE', 'Press Tending'), ('RI', 'Rubber Insertion'), ('SD', 'Screw Driving'), ('SE', 'Sealing'), ('SA', 'Small Parts Assembly'), ('SW', 'Spot Welding'), ('SP', 'Spraying'), ('TE', 'Testing'), ('UL', 'Unloading')], max_length=250, null=True)),
                ('label', models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger'), ('A', 'success'), ('W', 'warning')], max_length=1)),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='')),
                ('slogan', models.CharField(blank=True, max_length=100, null=True)),
                ('performance_rating', models.IntegerField(default=1)),
                ('customer_rating', models.IntegerField(default=1)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('working_range_image', models.ImageField(upload_to='robots/working_range_images/')),
                ('number_of_axes', models.IntegerField(default=6)),
                ('payload', models.IntegerField(default=1)),
                ('reach', models.FloatField(default=1)),
                ('repeatability', models.FloatField(default=1)),
                ('picking_cycle', models.FloatField(default=1)),
                ('mounting', multiselectfield.db.fields.MultiSelectField(choices=[('A', 'Any'), ('F', 'Floor'), ('W', 'Wall'), ('T', 'Tilted'), ('I', 'Invert Mount')], max_length=30)),
                ('weight', models.IntegerField(default=1)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.controller')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('axis_number', models.CharField(choices=[('1', 'J1'), ('2', 'J2'), ('3', 'J3'), ('4', 'J4'), ('5', 'J5'), ('6', 'J6'), ('7', 'J7')], max_length=10)),
                ('speed', models.DecimalField(decimal_places=3, default=1, max_digits=8)),
                ('movement_type', models.CharField(choices=[('R', 'Rotation'), ('A', 'Arm'), ('W', 'Wrist'), ('B', 'Bend'), ('T', 'Turn')], max_length=150)),
                ('robot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('slug', models.CharField(max_length=250)),
                ('name', models.CharField(blank=True, max_length=350, null=True)),
                ('attribute_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attributegroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
