# Generated by Django 3.1.7 on 2021-07-24 15:13

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='performance_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_calculator',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['general_performance_calculator', 'General Performance Calculator'], ['simple_value_calculator', 'Simple Value Calculator']], max_length=250, null=True),
        ),
    ]
