# Generated by Django 3.1.7 on 2021-07-17 09:32

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='product_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('IR', 'Industrial Robots'), ('RGV', 'RGV Robots'), ('CO', 'Cobots'), ('WM', 'Welding Machines')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('IR', 'Industrial Robots'), ('RGV', 'RGV Robots'), ('CO', 'Cobots'), ('WM', 'Welding Machines')], default='robot', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IR', 'Industrial Robots'), ('RGV', 'RGV Robots'), ('CO', 'Cobots'), ('WM', 'Welding Machines')], max_length=4),
        ),
        migrations.DeleteModel(
            name='Axis',
        ),
    ]
