# Generated by Django 3.1.7 on 2021-08-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210724_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='calculated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_calculator',
            field=models.CharField(blank=True, choices=[['general_performance_calculator', 'General Performance Calculator'], ['simple_value_calculator', 'Simple Value Calculator']], max_length=250, null=True),
        ),
    ]
