# Generated by Django 3.1.4 on 2020-12-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_player_savegame'),
    ]

    operations = [
        migrations.AddField(
            model_name='savegame',
            name='player_name',
            field=models.CharField(default='guest', max_length=50),
        ),
        migrations.AddField(
            model_name='savegame',
            name='top_score',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
